/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2018-08-03 03:48:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("jar:file:/C:/cygwin64/home/jts123/FinalProject/Internship/Tomcat/apache-tomcat-8.0.50/lib/webapps/ProjectTemplate/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425996670000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.8.RELEASE.jar", Long.valueOf(1533166003806L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1528933948414L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.7.RELEASE.jar", Long.valueOf(1528933944310L));
    _jspx_dependants.put("jar:file:/C:/cygwin64/home/jts123/FinalProject/Internship/Tomcat/apache-tomcat-8.0.50/lib/webapps/ProjectTemplate/WEB-INF/lib/spring-webmvc-5.0.8.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1532607906000L));
    _jspx_dependants.put("/WEB-INF/layouts/include.jsp", Long.valueOf(1533165535734L));
    _jspx_dependants.put("jar:file:/C:/cygwin64/home/jts123/FinalProject/Internship/Tomcat/apache-tomcat-8.0.50/lib/webapps/ProjectTemplate/WEB-INF/lib/tiles-jsp-3.0.8.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1506823684000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-3.0.8.jar", Long.valueOf(1528933948894L));
    _jspx_dependants.put("jar:file:/C:/cygwin64/home/jts123/FinalProject/Internship/Tomcat/apache-tomcat-8.0.50/lib/webapps/ProjectTemplate/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425996670000L));
    _jspx_dependants.put("jar:file:/C:/cygwin64/home/jts123/FinalProject/Internship/Tomcat/apache-tomcat-8.0.50/lib/webapps/ProjectTemplate/WEB-INF/lib/spring-webmvc-5.0.8.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1532607906000L));
    _jspx_dependants.put("jar:file:/C:/cygwin64/home/jts123/FinalProject/Internship/Tomcat/apache-tomcat-8.0.50/lib/webapps/ProjectTemplate/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425996670000L));
    _jspx_dependants.put("jar:file:/C:/cygwin64/home/jts123/FinalProject/Internship/Tomcat/apache-tomcat-8.0.50/lib/webapps/ProjectTemplate/WEB-INF/lib/spring-security-taglibs-4.2.7.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1528874458000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body class=\"tundra\">\n");
      out.write("\t<div id=\"bodyContentTile\" class=\"container\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<h1 class=\"underline col-sm-12\">Welcome to Last.FM Login!</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"well\">\n");
      out.write("\t\t\t\t<form action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" method=\"POST\" class=\"form\" data-dojo-type=\"dijit/form/Form\"\n");
      out.write("\t\t\t\t\tid=\"loginForm\" name=\"loginForm\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-sm-5\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"\" class=\"control-label\">Username: </label> \n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"username\"\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"username\" id=\"username\" data-dojo-id=\"username\"\n");
      out.write("\t\t\t\t\t\t\t\t   data-dojo-type=\"dijit/form/TextBox\"\n");
      out.write("\t\t\t\t\t\t\t\t   data-dojo-props=\"required: true\">\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-sm-5\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"\" class=\"control-label\">Password: </label> \n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" placeholder=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t   name=\"password\" id=\"password\" data-dojo-id=\"password\"\n");
      out.write("\t\t\t\t\t\t\t\t   data-dojo-type=\"dijit/form/TextBox\"\n");
      out.write("\t\t\t\t\t\t\t\t   data-dojo-props=\"required: true\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group col-sm-2\">\n");
      out.write("\t\t\t\t\t\t\t<button id=\"basicLoginBtn\" class=\"btn btn-primary btn-form\"\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"submit\" data-dojo-type=\"oreilly/types/form/Button\"\n");
      out.write("\t\t\t\t\t\t\t\tdata-dojo-props=\"spinOnClick: false\">Login\n");
      out.write("\t\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/login.jsp(11,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/loginProcess");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
