/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-06-13 23:39:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/messages.jsp", Long.valueOf(1528487752000L));
    _jspx_dependants.put("/head.jsp", Long.valueOf(1528489820000L));
    _jspx_dependants.put("/nav.jsp", Long.valueOf(1528753098000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write("<title>Intern Tracking</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<!-- Bootstrap import - Check https://ui.oreillyauto.com/ui to make sure you have the latest! -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"resources/css/oreillybs-3.3.5r2.min.css\">\r\n");
      out.write("<!--  Dojo Overrides for Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"resources/css/oreillybs-dojo-r13.min.css\">\r\n");
      out.write("<!--  Code formatting tool -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"resources/css/codemirror.min.css\">\r\n");
      out.write("<!--  Guide-specific CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"resources/css/pattern-library.css\">\r\n");
      out.write("<!-- JavaScript Library for Dojo (not required yet) -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"resources/js/dojo/1/dojo/dojo-common.js\"></script> -->\r\n");
      out.write("<!-- JavaScript Libraries for Code Formatting (not required yet) -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"resources/js/codemirror.js\"></script> -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"resources/js/util/formatting.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/styles.css\">");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"setActiveLink('homeLink');\">\r\n");
      out.write("\t<div id=\"bodyContentTile\" class=\"container\">\r\n");
      out.write("\t\t<!-- Provide Messages to the user when applicable  -->\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t<div id=\"successMessage\" data-dojo-attach-point=\"successNode\" class=\"alert alert-success hidden\">\r\n");
      out.write("\t\t\t\t\tSuccess!<br>\r\n");
      out.write("\t\t\t\t\t<ul id=\"successMessageList\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"errorMessage\" data-dojo-attach-point=\"errorNode\" class=\"alert alert-danger hidden\">\r\n");
      out.write("\t\t\t\t\tError!<br>\r\n");
      out.write("\t\t\t\t\t<ul id=\"errorMessageList\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"warningMessage\" data-dojo-attach-point=\"warningNode\" class=\"alert alert-warning hidden\">\r\n");
      out.write("\t\t\t\t\tWarning!<br>\r\n");
      out.write("\t\t\t\t\t<ul id=\"warningMessageList\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"alertMessage\" data-dojo-attach-point=\"infoNode\" class=\"alert alert-info  hidden\">\r\n");
      out.write("\t\t\t\t\tInformation!<br>\r\n");
      out.write("\t\t\t\t\t<ul id=\"alertMessageList\">\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\t");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div id=\"marginContainer\" class=\"col-sm-2\">\r\n");
      out.write("\t\t\t\t");
      out.write("\t\t\t\t\r\n");
      out.write("<!-- \r\n");
      out.write("   Build a nav \r\n");
      out.write("   You will want a div with the certain attributes for it to display properly\r\n");
      out.write("   Check out the UI Guide for details.\r\n");
      out.write("   \r\n");
      out.write("   The NAV should contain: \r\n");
      out.write("        An unordered list with child list items\r\n");
      out.write("        Each list item should contain an anchor that points to a page.\r\n");
      out.write("   \t\tPage=Home \t\t    Anchor points to index.jsp.        Set li class=\"navLink\" and li id=\"homeLink\"\r\n");
      out.write("   \t\tPage=Enroll Intern  Anchor points to enrollIntern.jsp. Set li class=\"navLink\" and li id=\"enrollInternLink\"\r\n");
      out.write("   \t\tPage=Milestones     Anchor points to milestones.jsp.   Set li class=\"navLink\" and id=\"milestoneLink\"\r\n");
      out.write("   \t\t\r\n");
      out.write("-->\r\n");
      out.write("<!-- Nav goes here -->\r\n");
      out.write("\t\t\t\t<div class=\"well well-nav sidebar affix-top\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"nav nav-list\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navLink\" id=\"homeLink\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"index.jsp\">Home</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navLink\" id=\"enrollInternLink\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"enrollIntern.jsp\">Enroll Intern</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"navLink\" id=\"milestoneLink\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"milestones.jsp\">Milestones</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-sm-8\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-9\">\r\n");
      out.write("\t\t\t\t\t\t<h1>Intern Tracking</h1>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-3\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"halftopmargin\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- \"Extra Credit.\" Can you filter your table?  -->\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" tabindex=\"0\" id=\"searchBox\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Filter\" onkeypress=\"filterInterns();\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Table goes here\r\n");
      out.write("\t\t\t\t\t\t\t The table should be responsive and striped\r\n");
      out.write("\t\t\t\t\t\t\t Check the course notes and/or the UI Guide\r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t The default table should contain 2 columns\r\n");
      out.write("\t\t\t\t\t\t\t \t\"Team Member ID\"\r\n");
      out.write("\t\t\t\t\t\t\t \t\"Team Member\"\r\n");
      out.write("\t\t\t\t\t\t\t \t\"Average\"\r\n");
      out.write("\t\t\t\t\t\t\t \t\r\n");
      out.write("\t\t\t\t\t\t\t The interns ID will be a hyperlink that takes you to \r\n");
      out.write("\t\t\t\t\t\t\t editIntern.jsp \r\n");
      out.write("\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t The default row (when no data is found) should be\r\n");
      out.write("\t\t\t\t\t\t\t \"No Records Found\" (colspan=\"3\") \r\n");
      out.write("\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Team MemberID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Team Member</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Average</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"3\">No Records Found</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table> -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"table table-striped\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Team Member ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Team Member</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>Average</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody id=\"myTbody\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script src=\"./resources/JS/script.js\"></script>\r\n");
      out.write("\t<script>initIndex();</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
